### ISSUE TITLE
YII_DEBUG depends on env.code

### ISSUE THREAD

**Issue by pythagor** [clevertech/YiiBoilerplate#21]
It's possible to add setting 'env.code' using for enabling/disabling debug depend on environment? I searched through the code but never this param not using. Thanks.

**Comment by tonydspaniard** [comment]
Will analyze code for a good solution

**Comment by rinatio** [comment]
+1. There is no easy way to enable/disable YII_DEBUG ...

**Comment by rmrevin** [comment]
+1

**Comment by hijarian** [comment]
There's no need to specify YII_DEBUG anymore. Application is in debug mode by default. To disable debug mode you have three options:
1. Make the file under the root of codebase called `PRODUCTION_MODE`.
2. Make it so that a variable `$_SERVER['PRODUCTION_MODE']` will exist and have a true-ish value.
3. Make it so that there'll be an environment variable called `PRODUCTION_MODE` and have a true-ish value.

Check the `common/check_prod_mode.php` file for details.
