### ISSUE TITLE
Need More Excamples Documentation

### ISSUE THREAD

**Issue by DrMabuse23** [clevertech/YiiBoilerplate#43]
1. Plz show me how how i can use the frontend  baseurl in Backend
2. I think some more information about the Handling was usefull

thx

**Comment by DrMabuse23** [comment]
i do this in my backend config 
Yii::setPathOfAlias('frontendBaseUrl', '/comm/frontend/www');

why? => i build a gallery module i save the images in the frontend but i need a preview in the backend

**Comment by DrMabuse23** [comment]
Ok next thing i put a user module in common. I logged in my Backend all cool. then i want to use Yii::app->user->isGuest in frontend ia not logged in how to resolve this ?

**Comment by hijarian** [comment]
We commonly put the 

``` php
'params' => array(
    'frontendUrl' => 'someurl',
)
```

inside the backend config. As this value is developer-dependent, it's usually in local configuration snippet.

As for authentication - YiiBooster is designed so that backend is totally separated from frontend. You should never have a reason to login to both entry points simultaneously. So if you want to login to backend, then to frontend, you should do it separately in both entry points.
