### ISSUE TITLE
how to generate the yii docs about this structure

### ISSUE THREAD

**Issue by yinhe** [clevertech/YiiBoilerplate#67]
i want to use this extension for generate the app docs like the yii docs style, but i dont know how to do

this is the extensions:
https://github.com/phpnode/Yii-Docs-Generator

**Comment by hijarian** [comment]
Man, just RTFM. Most possibly you cannot use the Yii-Docs-Generator for YiiBoilerplate-based application because that extension relies on some specific traditional structure of Yii-based application and YiiBoilerplate is all about changing that structure. It will just be unable to find the classes to document.
