### ISSUE TITLE
Frontend Assets Update

### ISSUE THREAD

**Issue by infoitservit** [clevertech/YiiBoilerplate#74]
I use "frontend/packages/main.css" as my css file for the frontend side.
If i change something and refresh a page, it doesn't update nothing. The asset still get an old/invalid main.css file.

To solve this problem i change the $frontend variable within FrontendController, (registerAssets() method) to:

"$frontend = $publisher->publish(ROOT_DIR . '/frontend/packages', false, 1, true);"

It forces asset to reload the css each time.

There is a way to do it easier? It is happen just to me?!

**Comment by hijarian** [comment]
It's design decision of Yii to have assets being republished when changed. I suppose we all have been purging `assets` directory after changing CSS files for ages.
By setting the republish flag to `true` you did the obvious thing which degraded performance of your application but allowed you to always have the most recent assets published.

The way to eliminate the need of republishing altogether is to place your assets in the publicly-available `css` directory inside webroot and register this fixed file instead of re-publishing anything. That's how it was done in the Yii autogenerated web application. If you have only a single stylesheet then probably it's the best solution for you.

**Comment by hijarian** [comment]
Also, you don't have to complain about any change you needed to make in the YiiBoilerplate code. Please understand that it's a _boilerplate code_, not a framework or library. You are _expected_ to change it according to your application specifics.
