### ISSUE TITLE
Problem with Behat installation

### ISSUE THREAD

**Issue by infoitservit** [clevertech/YiiBoilerplate#75]
I tried to use behat (bin/behat) but the response was something about the YAML component was missing. I check the proper folder and it was true, no files were inside the folder. I downloaded the yaml component from github and manually added it to the folder. Now it's working.

Why it wasn't automatically downloaded? Within the composer.json there is no trace of behat component also. Is it installed through mink?

Thanks!

**Comment by hijarian** [comment]
Composer packages `behat/behat` and `behat/mink` are installed as dependencies of `behat/mink-extension` to ensure proper versions compatibility. All problems with Composer-installed dependencies can be resolved by purging the `vendor` directory and re-running `php composer.phar install`, it's nothing special.

I just have cloned the repo and ran `php composer.phar self-update && php composer.phar update` from root of codebase. `symfony/yaml` installed correctly after that.

So, can you elaborate about how did you bring your instance of boilerplate to the state when the Behat will not launch because of missing dependency?

**Comment by infoitservit** [comment]
I will try to replicate the problem this weekend. Thanks

**Comment by infoitservit** [comment]
I've another problem, posted here http://www.yiiframework.com/forum/index.php/topic/50619-yii-boilerplate-and-unit-test-errors-and-configuration/page__p__235285__fromsearch__1#entry235285
