### ISSUE TITLE
user login session in applications

### ISSUE THREAD

**Issue by mhipo1364** [clevertech/YiiBoilerplate#78]
Hi 
I have an issue about user login session in frontend and backend applications.

It's better that each application(frontend, backend, ...) defined in separate virtual hosts; according to this assume, if administrator logins on backend, and want to go to frontend app , he has to re-login in frontend again. How can we manage it to keep login administrator in frontend and backend both.

**Comment by hijarian** [comment]
You know, it's even better if there'll be two separate tables for users at backend and frontend...

Nevertheless, you can possibly force a client to create a login cookie on _both_ domains. I mean the same cookie the "remember me" feature creates. I think it's the best route to follow, because PHP seems to have virtually no other means of preserving state between requests to different domains.
